from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any


def _as_dict(report: Any) -> dict[str, Any]:
    if hasattr(report, "to_dict"):
        return report.to_dict()
    if isinstance(report, dict):
        return report
    raise TypeError("report must be a ScanReport or dictionary")


def render_markdown(report: Any) -> str:
    data = _as_dict(report)
    findings = data.get("findings") or []
    top = findings[0] if findings else None
    dbms = data.get("dbms_profile") or {}
    dbms_text = ", ".join(f"{name} {score}%" for name, score in dbms.items()) or "Unknown"
    lines = [
        "# WebSQLMapper SQL Injection Assessment",
        "",
        "## Summary",
        "",
        f"- **Target:** `{data.get('target', '')}`",
        f"- **Method:** `{data.get('method', '')}`",
        f"- **Injection point:** `{data.get('injection_location', 'auto')}:{data.get('parameter', '')}`",
        f"- **Verdict:** **{data.get('verdict', 'unknown')}**",
        f"- **Confidence:** **{data.get('confidence_score', 0)}/100**",
        f"- **Reproducibility:** **{data.get('reproducibility', 0)}%**",
        f"- **Probable DBMS:** {dbms_text}",
        f"- **Requests sent:** {data.get('requests_sent', 0)}",
        f"- **Adaptive early-stop:** {'yes' if data.get('adaptive_stopped') else 'no'}",
        f"- **Interference profile:** {json.dumps(data.get('interference_profile') or {}, ensure_ascii=False)}",
        "- **CWE:** CWE-89 — Improper Neutralization of Special Elements used in an SQL Command",
        "",
        "## Evidence",
        "",
    ]
    if not findings:
        lines.append("No medium-or-higher confidence SQL injection indicator was confirmed.")
    for index, finding in enumerate(findings, 1):
        lines.extend([
            f"### {index}. {finding.get('title', 'Finding')}",
            "",
            f"- Score: {finding.get('score', 0)}/100",
            f"- Confidence: {finding.get('confidence', 'unknown')}",
            f"- Category: `{finding.get('category', '')}`",
            f"- DBMS hint: `{finding.get('dbms_hint') or 'none'}`",
            "",
            "```json",
            json.dumps(finding.get("evidence", {}), indent=2, ensure_ascii=False),
            "```",
            "",
        ])
    lines.extend([
        "## Reproduction timeline",
        "",
        "| # | Phase | Label | Status | Length | Time (ms) | Redirects |",
        "|---:|---|---|---:|---:|---:|---:|",
    ])
    for item in data.get("timeline") or []:
        lines.append(
            f"| {item.get('index')} | {item.get('phase')} | {item.get('label')} | "
            f"{item.get('status')} | {item.get('length')} | {item.get('elapsed_ms')} | {len(item.get('redirects') or [])} |"
        )
    redirect_rows = []
    for item in data.get("timeline") or []:
        for hop in item.get("redirects") or []:
            redirect_rows.append((item, hop))
    if redirect_rows:
        lines.extend([
            "",
            "## Redirect observations",
            "",
            "| Request | Hop | Status | Method | Source | Target | Cross host | HTTPS downgrade |",
            "|---:|---:|---:|---|---|---|---|---|",
        ])
        for item, hop in redirect_rows:
            lines.append(
                f"| {item.get('index')} | {hop.get('index')} | {hop.get('status')} | {hop.get('method')} | "
                f"`{hop.get('url')}` | `{hop.get('location')}` | {bool(hop.get('cross_host'))} | {bool(hop.get('https_downgrade'))} |"
            )
    lines.extend([
        "",
        "## Impact",
        "",
        "If the indicator is confirmed in the application context, SQL injection can allow an attacker to alter the intended database query. Actual impact depends on the affected statement and database privileges.",
        "",
        "## Remediation",
        "",
        "Use parameterized queries/prepared statements, allow-list any unavoidable dynamic identifiers, validate input by expected type, and give the application database account only the privileges it requires.",
        "",
        "## References",
        "",
        "- OWASP SQL Injection Prevention Cheat Sheet",
        "- PortSwigger Web Security Academy — SQL injection",
        "- CWE-89",
        "",
        "_Generated by WebSQLMapper. Review evidence manually before submitting a security report._",
    ])
    return "\n".join(lines) + "\n"


def render_html(report: Any) -> str:
    md = render_markdown(report)
    data = _as_dict(report)
    # Deliberately small self-contained report renderer; the original JSON is
    # included for precise evidence while the summary remains readable.
    return f"""<!doctype html>
<html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">
<title>WebSQLMapper report</title><style>
body{{font:15px/1.55 system-ui,sans-serif;background:#0b1118;color:#dce7f1;margin:0}}main{{max-width:1000px;margin:auto;padding:36px 20px}}
.card{{background:#111b26;border:1px solid #26384a;border-radius:16px;padding:20px;margin:16px 0}}h1,h2{{color:#ecf7ff}}code,pre{{font-family:ui-monospace,monospace}}pre{{white-space:pre-wrap;overflow:auto;background:#071018;padding:16px;border-radius:12px}}
strong{{color:#7fe0bb}}.score{{font-size:2rem;font-weight:800}}</style></head><body><main>
<h1>WebSQLMapper SQL Injection Assessment</h1>
<div class=\"card\"><div class=\"score\">{html.escape(str(data.get('confidence_score', 0)))}/100</div>
<p><strong>{html.escape(str(data.get('verdict', 'unknown')))}</strong> · reproducibility {html.escape(str(data.get('reproducibility', 0)))}%</p>
<p>{html.escape(str(data.get('method', '')))} {html.escape(str(data.get('target', '')))}</p></div>
<div class=\"card\"><h2>Markdown report</h2><pre>{html.escape(md)}</pre></div>
<div class=\"card\"><h2>Machine-readable evidence</h2><pre>{html.escape(json.dumps(data, indent=2, ensure_ascii=False))}</pre></div>
</main></body></html>"""


def render_report(report: Any, format_name: str) -> str:
    format_name = format_name.lower()
    if format_name == "json":
        return json.dumps(_as_dict(report), indent=2, ensure_ascii=False) + "\n"
    if format_name == "markdown":
        return render_markdown(report)
    if format_name == "html":
        return render_html(report)
    raise ValueError("report format must be one of: json, markdown, html")


def load_report(path: str | Path) -> dict[str, Any]:
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except OSError as exc:
        raise ValueError(f"cannot read report: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid JSON report: {exc.msg}") from exc
    if not isinstance(data, dict):
        raise ValueError("JSON report root must be an object")
    return data
